In [17]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset
dataset=pd.read_csv("/kaggle/input/diabeteessss/diabetesworkonthis.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


In [22]:
X[:,1]

array([148.,  85., 183.,  89., 137., 116.,  78., 115., 197., 125., 110.,
       168., 139.,  nan, 166., 100., 118., 107., 103., 115., 126.,  99.,
       196., 119., 143., 125., 147.,  97., 145., 117., 109., 158.,  88.,
        92., 122., 103., 138., 102.,  90., 111., 180., 133., 106., 171.,
       159., 180., 146.,  71., 103., 105., 103., 101.,  88., 176., 150.,
        73., 187., 100., 146., 105.,  84., 133.,  44., 141., 114.,  99.,
       109., 109.,  95., 146., 100., 139., 126., 129.,  79.,   0.,  62.,
        95., 131., 112., 113.,  74.,  83., 101., 137., 110., 106., 100.,
       136., 107.,  80., 123.,  81., 134., 142., 144.,  92.,  71.,  93.,
       122., 163., 151., 125.,  81.,  85., 126.,  96., 144.,  83.,  95.,
       171., 155.,  89.,  76., 160., 146., 124.,  78.,  97.,  99., 162.,
       111., 107., 132., 113.,  88., 120., 118., 117., 105., 173., 122.,
       170.,  84.,  96., 125., 100.,  93., 129., 105., 128., 106., 108.,
       108., 154., 102.,  57., 106., 147.,  90., 13

In [24]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy = 'mean', missing_values = np.nan)
imputer=imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])


In [25]:
X[:,1]

array([148.        ,  85.        , 183.        ,  89.        ,
       137.        , 116.        ,  78.        , 115.        ,
       197.        , 125.        , 110.        , 168.        ,
       139.        , 120.11722913, 166.        , 100.        ,
       118.        , 107.        , 103.        , 115.        ,
       126.        ,  99.        , 196.        , 119.        ,
       143.        , 125.        , 147.        ,  97.        ,
       145.        , 117.        , 109.        , 158.        ,
        88.        ,  92.        , 122.        , 103.        ,
       138.        , 102.        ,  90.        , 111.        ,
       180.        , 133.        , 106.        , 171.        ,
       159.        , 180.        , 146.        ,  71.        ,
       103.        , 105.        , 103.        , 101.        ,
        88.        , 176.        , 150.        ,  73.        ,
       187.        , 100.        , 146.        , 105.        ,
        84.        , 133.        ,  44.        , 141.  

In [26]:
y

array([ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.,  1.,  0.,  1.,  0.,
       nan,  1.,  1.,  1.,  1.,  0.,  1.,  0.,  0., nan,  1.,  1.,  1.,
        1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,
        0.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  0.,  0.,
        0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  1.,  1.,
        1.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  1.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,  0.,  0.,
        0.,  1.,  1.,  0.,  0.,  0.,  1.,  0.,  1.,  0.,  1.,  0

In [27]:
#spliting the dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X,y,test_size=0.1,random_state=0)


In [30]:

y_test

array([0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 1., 0., 1., 1.])

In [31]:
X_train

array([[  3.   , 128.   ,  78.   , ...,  21.1  ,   0.268,  55.   ],
       [  7.   , 107.   ,  74.   , ...,  29.6  ,     nan,  31.   ],
       [  0.   , 101.   ,  62.   , ...,  21.9  ,   0.336,  25.   ],
       ...,
       [  1.   , 196.   ,  76.   , ...,  36.5  ,   0.875,  29.   ],
       [  7.   , 159.   ,  66.   , ...,  30.4  ,   0.383,  36.   ],
       [ 11.   ,  85.   ,  74.   , ...,  30.1  ,   0.3  ,  35.   ]])

In [32]:
X_test

array([[0.000e+00, 1.040e+02, 7.600e+01, 0.000e+00, 0.000e+00, 1.840e+01,
        5.820e-01, 2.700e+01],
       [3.000e+00, 9.900e+01, 8.000e+01, 1.100e+01, 6.400e+01, 1.930e+01,
        2.840e-01, 3.000e+01],
       [8.000e+00, 1.090e+02, 7.600e+01, 3.900e+01, 1.140e+02, 2.790e+01,
        6.400e-01, 3.100e+01],
       [3.000e+00, 1.150e+02, 6.600e+01, 3.900e+01, 1.400e+02, 3.810e+01,
        1.500e-01, 2.800e+01],
       [1.000e+00, 1.430e+02, 8.400e+01, 2.300e+01, 3.100e+02, 4.240e+01,
        1.076e+00, 2.200e+01],
       [1.000e+01, 1.290e+02, 7.600e+01, 2.800e+01, 1.220e+02, 3.590e+01,
        2.800e-01, 3.900e+01],
       [4.000e+00, 1.440e+02, 8.200e+01, 3.200e+01, 0.000e+00, 3.850e+01,
        5.540e-01, 3.700e+01],
       [1.000e+00, 1.250e+02, 7.000e+01, 2.400e+01, 1.100e+02, 2.430e+01,
        2.210e-01, 2.500e+01],
       [9.000e+00, 1.450e+02, 8.800e+01, 3.400e+01, 1.650e+02, 3.030e+01,
        7.710e-01, 5.300e+01],
       [3.000e+00, 1.390e+02, 5.400e+01, 0.000e+00, 0.0

In [38]:
#Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset
dataset=pd.read_csv("/kaggle/input/1stdemowork/Data.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [39]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [40]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [41]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy = 'mean', missing_values = np.nan)
imputer=imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])


In [42]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [43]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,0]=labelencoder_X.fit_transform(X[:,0])

from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [0])],   
    remainder='passthrough'                                         
)
X = ct.fit_transform(X)

labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [44]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [45]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [49]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset
dataset=pd.read_csv("/kaggle/input/2ndtestingfile/facebook.csv")
X=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [50]:
#encoding on the other dataset
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X=LabelEncoder()
X[:,1]=labelencoder_X.fit_transform(X[:,1])

from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [1])],   
    remainder='passthrough'                                         
)
X = ct.fit_transform(X)

labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [51]:
X[:,1]

array([0.0, 1.0, 0.0, ..., 1.0, 1.0, 1.0], dtype=object)

In [52]:
X[:,:]

array([[0.0, 0.0, 0.0, ..., 3, 1, 1],
       [0.0, 1.0, 0.0, ..., 0, 0, 0],
       [0.0, 0.0, 0.0, ..., 1, 1, 0],
       ...,
       [0.0, 1.0, 0.0, ..., 0, 0, 0],
       [0.0, 1.0, 0.0, ..., 0, 0, 0],
       [0.0, 1.0, 0.0, ..., 0, 0, 0]], dtype=object)